spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/forefilm
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create # this setting is for local test. It needs to change to 'none' later.